owner: longbridgeapp
repo: uptime
status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/longbridgeapp/uptime/master/assets/upptime-icon.svg
  name: Longbridge Uptime
  introTitle: "Longbridge **Uptime**"
  introMessage: This is uptime monitor for Longbridge.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

sites:
  - name: Longbridge Web (longbridgeapp.com)
    url: https://longbridgeapp.com
    headers:
      - "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
    expectedStatusCodes:
      - 302
      - 301
    assignees:
      - ihavecoke
  - name: LongPort Web (longportapp.com)
    url: https://longportapp.com
    headers:
      - "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
    expectedStatusCodes:
      - 200
    assignees:
      - ihavecoke
  - name: LongPort Web CN (longportapp.cn)
    url: https://longportapp.cn
    headers:
      - "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
    expectedStatusCodes:
      - 200
    assignees:
      - ihavecoke
  - name: 小程序 - 个股详情页面 (via longbridgeapp.com)
    url: https://longbridgeapp.com/quote/00700.HK?source_app=longbridge
    headers:
      - "User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; MI 6 Build/NMF26X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 MQQBrowser/6.2 TBS/043807 Mobile Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/4G Language/zh_CN MicroMessenger/6.6.1.1220(0x26060135) NetType/4G Language/zh_CN miniProgram"
    expectedStatusCodes:
      - 200
    assignees:
      - ihavecoke

  # Legacy
  - name: lbkrs.com -> longportapp.com
    url: https://lbkrs.com
    expectedStatusCodes:
      - 301

  # Download pages
  - name: Download - Longbridge App (Legacy)
    url: https://longbridgeapp.com/download
    expectedStatusCodes:
      - 302
    assignees:
      - ihavecoke
  - name: Download - LongPort App (Legacy)
    url: https://longportapp.com/longport/download
    assignees:
      - ihavecoke
  - name: Download - Longbridge App
    url: https://longportapp.com/download/longbridge
    assignees:
      - ihavecoke
  - name: Download - LongPort App
    url: https://longportapp.com/download
  - name: Download - Longbridge App QRCode (Legacy)
    url: https://longbridgeapp.com/download/qr
    expectedStatusCodes:
      - 302
  - name: Download - Longbridge App QRCode (Legacy)
    url: https://longportapp.com/download/qr?app_id=longbridge
  - name: Download - Activity Download (Legacy)
    url: https://activity.lbkrs.com/m/download
    expectedStatusCodes:
      - 302
  - name: H5 - Portal App Download
    url: https://m.lbkrs.com/app/download
    expectedStatusCodes:
      - 302

  # LongPort Web - Pages
  - name: LongPort Web - 公告 - 列表
    url: https://longportapp.com/announcements
    assignees:
      - hold-baby
  - name: LongPort Web - 资讯列表
    url: https://longportapp.com/news
    assignees:
      - hold-baby
  - name: LongPort Web - 资讯 - 长桥日报
    url: https://longportapp.com/news/node/daily
    assignees:
      - hold-baby
  - name: LongPort Web - 资讯 - 动态新闻
    url: https://longportapp.com/news/node/dynamic
    assignees:
      - hold-baby
  - name: LongPort Web - 资讯 - 海豚投研
    url: https://longportapp.com/news/dolphin
    assignees:
      - hold-baby
  - name: LongPort Web - 资讯 - 长桥资讯
    url: https://longportapp.com/news/information
    assignees:
      - hold-baby
  - name: LongPort Web - 资讯阅读页面
    url: https://longportapp.com/news/75979678
    assignees:
      - hold-baby
  - name: LongPort Web - 个人 Profile
    url: https://longportapp.com/profiles/6539443
    assignees:
      - hold-baby
  - name: LongPort Web - 个人主页 - 原创列表
    url: https://longportapp.com/profiles/6539443
    assignees:
      - hold-baby
  - name: LongPort Web - 个人主页 - 关注者列表
    url: https://longportapp.com/profiles/6539443/followers
    assignees:
      - hold-baby
  - name: LongPort Web - 个人主页 - 关注列表
    url: https://longportapp.com/profiles/6539443/followers
    assignees:
      - hold-baby
  - name: LongPort Web - 个人主页 - 股票视图
    url: https://longportapp.com/profiles/6539443/stocks-view
    assignees:
      - hold-baby
  - name: LongPort Web - Hashtag 话题 - 详情列表
    url: https://longportapp.com/hash/310330
    assignees:
      - hold-baby
  - name: LongPort Web - 话题 - 详情热门列表
    url: https://longportapp.com/hash/310330/hot
    assignees:
      - hold-baby
  - name: LongPort Web - Login
    url: https://longbridgeapp.com/login
  - name: LongPort Web - Forget Password
    url: https://longportapp.com/password/reset
  - name: LongPort Web - 媒体报道
    url: https://longportapp.com/report
  - name: LongPort Web - 企业员工认证
    url: https://longbridgeapp.com/company-verify
  - name: LongPort Web - Jobs
    url: https://longbridgeapp.com/jobs?city=jobs-sg
  - name: LongPort Web - Jobs - Detail
    url: https://longbridgeapp.com/jobs/45tnnqw?city=jobs-sg
  - name: LongPort Web - 股单介绍
    url: https://longbridgeapp.com/sharelist/126690

  # LongPort Feed API
  - name: LongPort Feed - News
    url: https://longbridgeapp.com/news/feed
  - name: LongPort Feed - Live
    url: https://longbridgeapp.com/news/live/feed
  - name: LongPort Feed - Live
    url: https://longbridgeapp.com/news/live/feed
  - name: LongPort Feed - Topic
    url: https://longbridgeapp.com/topics/feed
  - name: LongPort Feed - News of BABA.US
    url: https://longbridgeapp.com/quote/BABA.US/news/feed

  # LongPort Sitemap
  - name: LongPort Sitemap - News (Page)
    url: https://longportapp.com/sitemap/news.html
  - name: LongPort Sitemap - News (XML)
    url: https://longportapp.com/news/sitemap
  - name: LongPort Sitemap - Topic (Page)
    url: https://longportapp.com/sitemap/topics.html
  - name: LongPort Sitemap - Stock (Page)
    url: https://longportapp.com/sitemap/quote.html
  - name: LongPort Sitemap - Live (Page)
    url: https://longportapp.com/sitemap/lives.html
  - name: LongPort Sitemap - Live (XML)
    url: https://longbridgeapp.com/news/live/sitemap

  # Activity 活动页面
  - name: Activity - 2022NewAct (CN)
    url: https://activity.lbkrs.com/pipeline/2022NewAct/index.html
    assignees:
      - dearest
  - name: Activity - 2022NewAct (HK)
    url: https://activity.longbridgehk.com/pipeline/2022NewAct/index.html
    assignees:
      - dearest
  - name: Activity - 港美股免佣特权 (CN)
    url: https://activity.lbkrs.com/pipeline/commission_invite/index.html
  - name: Activity - 港美股免佣特权 (HK)
    url: https://activity.longbridgehk.com/pipeline/commission_invite/index.html
  - name: Activity - 交易期权领苹果 14 (CN)
    url: https://activity.lbkrs.com/pipeline/option10/index.html?sac=lb&businessType=activity&lbFitsStatusBar=0&invite-code=845490
  - name: Activity - 交易期权领苹果 14 (HK)
    url: https://activity.longbridgehk.com/pipeline/option10/index.html?sac=lb&businessType=activity&lbFitsStatusBar=0&invite-code=845490

  # Portal Page (以下的是 App 内在用的)
  - name: H5 - 资讯阅读页面
    url: https://m.lbkrs.com/news/post/76049490
  - name: H5 - 资讯阅读页面 - PDF
    url: https://m.lbkrs.com/news/post/76049490/dr-pdf
  - name: H5 - 社区长文
    url: https://m.lbkrs.com/social/1888673
  - name: H5 - 个股季报
    url: https://activity.lbkrs.com/zh-CN/lightning/financial-report?counterId=ST%2FUS%2FBABA&need_login=0&lblang=zh-CN&lbtheme=dark&lbapp=1
  - name: H5 - 产业链
    url: https://app.lbkrs.com/community/industrial-chains/1483?share=true
  - name: H5 - Who's LEO
    url: https://longbridgeapp.com/leo
  - name: H5 - 获取服务端时间
    url: https://m.lbkrs.com/api/_ping
  - name: H5 - 超链接白名单跳转 (Block)
    url: https://m.lbkrs.com/link?url=https://foobar.com
  - name: H5 - 超链接白名单跳转 (Pass)
    url: https://m.lbkrs.com/link?url=https://longbridge.hk
    expectedStatusCodes:
      - 302
  - name: H5 - 学院课程
    url: https://longportapp.com/community/course/56

  # Help Center (以下的是 App 内在用的)
  - name: Help - Longbridge HK
    url: https://support.longbridge.hk
  - name: Help - Longbridge HK (.com)
    url: https://support.longbridgehk.com
  - name: Help - 关于 Longbridge
    url: https://support.longbridgehk.com/topics/us-trade/about-lb
  - name: Help - 行情数据字段介绍
    url: https://support.longbridgehk.com/topics/base/stock-fields
  - name: Help - 美股盘前盘后行情说明
    url: https://support.longbridgehk.com/topics/us-trade/us-pre-post-mkt-intro
  - name: Help - 资金流向数据说明
    url: https://support.longbridgehk.com/topics/base/capital_flow
  - name: Help - 订单有效期说明
    url: https://support.longbridgehk.com/topics/base/validperiod
  - name: Help - 总资产字段说明
    url: https://support.longbridgehk.com/topics/48l80xd/fwyeg9
  - name: Help - 免责声明
    url: https://support.longbridgehk.com/topics/misc/3isdzoe
  - name: Help - 长桥服务协议
    url: https://support.longbridgehk.com/topics/us-trade/user-agreement
  - name: Help - 社区协议
    url: https://support.longbridgeapp.com/topics/misc/cr7cva
  - name: Help - 行情使用免责声明
    url: https://support.longbridgeapp.com/topics/misc/market-data-disclaimer?
