owner: longbridgeapp
repo: upptime

sites:
  - name: Longbridge Web (longbridgeapp.com)
    url: https://longbridgeapp.com
    headers:
      - "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
    expectedStatusCodes:
      - 302
      - 301
  - name: LongPort Web (longportapp.com)
    url: https://longportapp.com
    headers:
      - "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
  - name: LongPort Web CN (longportapp.cn)
    url: https://longportapp.cn
  - name: 小程序 - 个股详情页面 (via longbridgeapp.com)
    url: https://longbridgeapp.com/quote/00700.HK?source_app=longbridge
    headers:
      - "User-Agent": "Mozilla/5.0 (Linux; Android 7.1.1; MI 6 Build/NMF26X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 MQQBrowser/6.2 TBS/043807 Mobile Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/4G Language/zh_CN MicroMessenger/6.6.1.1220(0x26060135) NetType/4G Language/zh_CN miniProgram"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Longbridge Upptime
  introTitle: "Longbridge **Upptime**"
  introMessage: This is uptime monitor for Longbridge.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
