on:
  issues:
    types: [opened]
jobs:
  build:
    name: Feishu Bot
    runs-on: ubuntu-latest
    steps:
      - name: Feishu Bot Nessage
        uses: whatwewant/action-robot-feishu@v0.0.1
        with:
          url: ${{ secrets.FEISHU_WEBHOOK_URL }}
          title: Uptime Warning
          text: |
            ${{ github.issue.title }}

            ${{ github.issue.url }}

            ${{ github.issue.body }}
